### PR TITLE
Add link to simplified Chinese version

### PR DESCRIPTION
**Pull request by TeddyHuang-00**
Finished translation work of this repo, so added a link in the main repo for quick jump

### CODE REVIEW

**Comment by cht8687** [comment]
Hi @TeddyHuang-00 
thanks for this PR. is it possible to put the Chinese version under this same repo?

**Comment by TeddyHuang-00** [comment]
@cht8687 sure! my honor to do so. I'll open another pull request for this.

**Comment by TeddyHuang-00** [comment]
@cht8687 Sorry for my mistake here, as I found out that I don't have to open a new PR, and the adjustment has been made as your suggestion. :D

**Review by cht8687 — APPROVED** [review]

**Comment by cht8687** [comment]
thanks @TeddyHuang-00 
I had requested @stevemao for another check. 
looks good to me.

**Comment by TeddyHuang-00** [comment]
pleasure to do so @cht8687

**Comment by stevemao** [comment]
absolutely amazing! Thanks!

**Pull request merged**
