### PR TITLE
Add ping command

### PR DESCRIPTION
**Pull request by umr55766**
I see that other commands don't have an example separately, Please let me if I should also only include syntax or example, I'll be more than happy to update this.

### CODE REVIEW

**Comment by cht8687** [comment]
:+1:

**Comment by cht8687** [comment]
some conflicts :smile:

**Comment by umr55766** [comment]
Conflicts resolved! 😉

**Comment by stevemao** [comment]
@umr55766 I merged the other PR this has conflicts again... Sorry

**Comment by umr55766** [comment]
No problem man @stevemao  👍  Resolved!

**Comment by stevemao** [comment]
Thanks a lot!

**Pull request merged**
