### PR TITLE
Removed ridiculously ridiculous comments

### PR DESCRIPTION
**Pull request by Patrick-Spiegel**

### CODE REVIEW

**Comment by stevemao** [comment]
How is that ridiculous?

**Comment by Patrick-Spiegel** [comment]
The declared purpose of this repo is to show commands to use in scripts.

Suggesting to switch into cli mode while working in gui mode is just a bad advice. Switching interfaces mid work is inefficient.

**Comment by celestiallake** [comment]
Depends highly on the UI implementation you use. If you're working with a tiling WM, you're ok to use CLI features. They make sense there since most TWMs are designed to be the enhanced graphical terminal multiplexers. They are intended to be used with CLI-based applications and serve as the way to easily access applications that don't fit into that paradigm properly.

On the other hand, is this article even relevant when we talk of i3 users and other fancy folk?

As of switching... Quake-style terminal emulators were invented for this. Using Gnome, for example, you can quickly switch back and forth via the Guake project. I'd not name that ease an inefficient one.

**Comment by Berkmann18** [comment]
@Patrick-Spiegel Look at it this way: why would a person open a directory with which file manager he/she has just to: rename/delete/open a file/directory, ...; when it can be done in the CLI?

**Comment by nrdxp** [comment]
@Patrick-Spiegel ever heard of a tiling window manager? I literally use nothing but a browser and terminal in sway and I rarely need anything else. With the convenience of zsh completions, fzf (or skim in my case) and a few well chosen aliases nothing is ever more than a few keystrokes. This PR should probably be closed.

**Pull request closed without merging**
